### PR TITLE
Add color to the gender label

### PR DESCRIPTION
**Pull request by tanyqcollin**
Screenshot 2024-10-11 112629
Add symbol and color to the gender

- If the `gender` is `male`, the font color will be light blue.
- If the `gender` is `female`, the font color will be pink.

### CODE REVIEW

**Review by Jianwen0451 — COMMENTED** [review]
Generally Look good to me, I think just need to add the test cases to Person card to pass the code ev requirement then OK

**Comment by tanyqcollin** [comment]
> Generally Look good to me, I think just need to add the test cases to Person card to pass the code ev requirement then OK

**Comment by tanyqcollin** [comment]
@Jianwen0451 I think i have same issue with Isaac because the person card is a Ui and it is not tested at the beginning.

**Review by RadieonAjax — APPROVED** [review]
Looks good to me! There is implicit testing for the coloring, hence the codecov warning can be ignored.

**Pull request merged**
